package objectRepository;

import org.openqa.selenium.By;

public class MobilePage {
	
	public static By txtHome = By.xpath("//div[@class='page-title']");
	public static By lnkMobile = By.linkText("MOBILE");
	public static By txtMobile = By.xpath("//div[@class='page-title category-title']");
	public static By ddMobile = By.xpath("//select[@title='Sort By']");
	public static By txtSonyPrice = By.xpath("//span[contains(text(),'$100.00')]");
	public static By lnkSony = By.linkText("SONY XPERIA");
	public static By btnAddtoCart = By.xpath("//button[@title='Add to Cart']");
	public static By lnkEdit = By.linkText("Edit");
	public static By txtQty = By.name("qty");
	public static By btnUpdate = By.xpath("//button[@title='Update Cart']");
	public static By txtError = By.xpath("/html/body/div/div/div[2]/div/div/div/ul/li/ul/li/span");
	public static By lnkEmptyCart = By.id("empty_cart_button");
	public static By txtTitle = By.xpath("//div[@class='page-title']");
	public static By txtSony = By.xpath("//a[@title='Sony Xperia']");
	public static By txtIPhone = By.xpath("/html/body/div/div/div[2]/div/div[2]/div[1]/div[3]/ul/li[2]/div/h2/a");
	public static By lnkSonyCom = By.xpath("/html/body/div/div/div[2]/div/div[2]/div[1]/div[3]/ul/li[1]/div/div[3]/ul/li[2]/a");
	public static By lnkIPHCom = By.xpath("/html/body/div/div/div[2]/div/div[2]/div[1]/div[3]/ul/li[2]/div/div[3]/ul/li[2]/a");
	public static By btnCompare = By.xpath("//button[@title='Compare']");
	public static By txtCompare = By.xpath("//div[@class='page-title title-buttons']");
	public static By txtSonyPopup = By.xpath("/html/body/div/table/tbody[1]/tr[1]/td[1]/h2/a");
	public static By txtIphPopup = By.xpath("/html/body/div/table/tbody[1]/tr[1]/td[2]/h2/a");
	public static By btnClose = By.xpath("//button[@title='Close Window']");
	public static By lnkMyaccount = By.linkText("MY ACCOUNT");
	public static By btnCreateAC = By.xpath("//a[@title='Create an Account']");
	public static By txtFirstname = By.id("firstname");
	public static By txtLastName = By.id("lastname");
	public static By txtEmailID = By.id("email_address");
	public static By txtPwd = By.id("password");
	public static By txtCnfPwd = By.id("confirmation");
	public static By chkNewsletter = By.xpath("//label[@for='is_subscribed']");
	public static By btnRegister = By.xpath("//button[@title='Register']");
	public static By lnkTV = By.linkText("TV");
	public static By lnkWishList = By.className("link-wishlist");
	public static By btnWishList = By.xpath("//button[@title='Share Wishlist']");
	public static By txtEID = By.id("email_address");
	public static By txtMsg = By.id("message");
	public static By txtSuccessMsg = By.className("success-msg");
	public static By txtEnterEmail = By.name("login[username]");
	public static By txtEnterPwd = By.id("pass");
	public static By btnLogin = By.id("send2");
	public static By lnkMyWish = By.linkText("MY WISHLIST");
	public static By btnAddcart = By.xpath("//button[@title='Add to Cart']");
	public static By btnCheckout = By.xpath("//button[@title='Proceed to Checkout']");
	public static By txtAddress = By.id("billing:street1");
	public static By txtCity = By.id("billing:city");
	public static By ddProvice = By.id("billing:region_id");
	public static By txtZip = By.id("billing:postcode");
	public static By ddCountry= By.id("billing:country_id");
	public static By txtTelephone = By.id("billing:telephone");
	public static By btnContinue = By.xpath("//button[@title='Continue']");
	public static By ddSProvince = By.id("region_id");
	public static By txtSZip = By.id("postcode");
	public static By btnEstimate = By.xpath("//button[@title='Estimate']");
	public static By radioFlat = By.id("s_method_flatrate_flatrate");
	public static By btnUpdateTotal = By.xpath("//button[@title='Update Total']");
	public static By txtCartPrice = By.xpath("//*[@id=\'shopping-cart-totals-table\']/tbody/tr[1]/td[2]/span");
	public static By txtFlatPrice = By.xpath("//*[@id=\'shopping-cart-totals-table\']/tbody/tr[2]/td[2]/span");
	public static By txtTotalPrice = By.xpath("//*[@id=\'shopping-cart-totals-table\']/tfoot/tr/td[2]/strong/span");
	public static By btnSContinue = By.xpath("/html/body/div/div/div[2]/div/div[1]/ol/li[3]/div[2]/form/div[3]/button");
	public static By radioPayment = By.id("p_method_checkmo");
	public static By btnPContinue = By.xpath("//*[@id=\'payment-buttons-container\']/button");
	public static By btnPlaceOrder = By.xpath("//*[@id=\"review-buttons-container\"]/button");
	public static By txtOrderNumber = By.xpath(".//*[@id='top']/body/div[1]/div/div[2]/div/div/p[1]/a");
	public static By lnkMyOrder = By.linkText("MY ORDERS");
	public static By txtOrderNo = By.xpath("/html/body/div/div/div[2]/div/div[2]/div/table/tbody/tr[1]/td[1]");
	public static By txtOrderStatus = By.xpath("/html/body/div/div/div[2]/div/div[2]/div/table/tbody/tr[1]/td[5]");
	public static By txtOrder = By.xpath("/html/body/div/div/div[2]/div/div[2]/div/table/tbody/tr[1]/td[6]/span/a[1]");
	public static By printOrder = By.linkText("Print Order");
	public static By reOrder = By.linkText("REORDER");
	public static By grandTotal = By.xpath("/html/body/div/div/div[2]/div/div/div/div[3]/div/table/tfoot/tr/td[2]/strong/span");
	public static By btnAddIphone = By.xpath("/html/body/div/div/div[2]/div/div[2]/div[1]/div[3]/ul/li[2]/div/div[3]/button");
	public static By txtDiscount = By.id("coupon_code");
	public static By lnkApply = By.xpath("//button[@title='Apply']");
	public static By txtGrandTotalDis = By.xpath("/html/body/div/div/div[2]/div/div/div/div[3]/div/table/tfoot/tr/td[2]");
	public static By txtTotalDis = By.xpath("/html/body/div/div/div[2]/div/div/div/div[3]/div/table/tbody/tr[2]/td[2]");
	public static By txtUserback = By.id("username");
	public static By txtPwdback = By.id("login");
	public static By btnLoginback = By.xpath("//input[@title='Login']");
	public static By winPopup = By.id("message-popup-window");
	public static By closePopup = By.xpath("//a[@title='close']");
	public static By lnkBackSales = By.linkText("Sales");
	public static By lnkBackOrder = By.linkText("Orders");
	public static By ddCSV = By.id("sales_order_grid_export");
	public static By btnExport = By.xpath("//button[@title='Export']");
}
